/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToastRouteImport } from './routes/toast'
import { Route as TabsRouteImport } from './routes/tabs'
import { Route as TableRouteImport } from './routes/table'
import { Route as SeparatorRouteImport } from './routes/separator'
import { Route as ScrollAreaRouteImport } from './routes/scroll-area'
import { Route as PreviewCardRouteImport } from './routes/preview-card'
import { Route as PopoverRouteImport } from './routes/popover'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as FormRouteImport } from './routes/form'
import { Route as DialogsRouteImport } from './routes/dialogs'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as IndexRouteImport } from './routes/index'

const ToastRoute = ToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const SeparatorRoute = SeparatorRouteImport.update({
  id: '/separator',
  path: '/separator',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollAreaRoute = ScrollAreaRouteImport.update({
  id: '/scroll-area',
  path: '/scroll-area',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewCardRoute = PreviewCardRouteImport.update({
  id: '/preview-card',
  path: '/preview-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PopoverRoute = PopoverRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogsRoute = DialogsRouteImport.update({
  id: '/dialogs',
  path: '/dialogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/button': typeof ButtonRoute
  '/dialogs': typeof DialogsRoute
  '/form': typeof FormRoute
  '/menu': typeof MenuRoute
  '/popover': typeof PopoverRoute
  '/preview-card': typeof PreviewCardRoute
  '/scroll-area': typeof ScrollAreaRoute
  '/separator': typeof SeparatorRoute
  '/table': typeof TableRoute
  '/tabs': typeof TabsRoute
  '/toast': typeof ToastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/button': typeof ButtonRoute
  '/dialogs': typeof DialogsRoute
  '/form': typeof FormRoute
  '/menu': typeof MenuRoute
  '/popover': typeof PopoverRoute
  '/preview-card': typeof PreviewCardRoute
  '/scroll-area': typeof ScrollAreaRoute
  '/separator': typeof SeparatorRoute
  '/table': typeof TableRoute
  '/tabs': typeof TabsRoute
  '/toast': typeof ToastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/button': typeof ButtonRoute
  '/dialogs': typeof DialogsRoute
  '/form': typeof FormRoute
  '/menu': typeof MenuRoute
  '/popover': typeof PopoverRoute
  '/preview-card': typeof PreviewCardRoute
  '/scroll-area': typeof ScrollAreaRoute
  '/separator': typeof SeparatorRoute
  '/table': typeof TableRoute
  '/tabs': typeof TabsRoute
  '/toast': typeof ToastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/button'
    | '/dialogs'
    | '/form'
    | '/menu'
    | '/popover'
    | '/preview-card'
    | '/scroll-area'
    | '/separator'
    | '/table'
    | '/tabs'
    | '/toast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/button'
    | '/dialogs'
    | '/form'
    | '/menu'
    | '/popover'
    | '/preview-card'
    | '/scroll-area'
    | '/separator'
    | '/table'
    | '/tabs'
    | '/toast'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/button'
    | '/dialogs'
    | '/form'
    | '/menu'
    | '/popover'
    | '/preview-card'
    | '/scroll-area'
    | '/separator'
    | '/table'
    | '/tabs'
    | '/toast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarRoute: typeof AvatarRoute
  ButtonRoute: typeof ButtonRoute
  DialogsRoute: typeof DialogsRoute
  FormRoute: typeof FormRoute
  MenuRoute: typeof MenuRoute
  PopoverRoute: typeof PopoverRoute
  PreviewCardRoute: typeof PreviewCardRoute
  ScrollAreaRoute: typeof ScrollAreaRoute
  SeparatorRoute: typeof SeparatorRoute
  TableRoute: typeof TableRoute
  TabsRoute: typeof TabsRoute
  ToastRoute: typeof ToastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toast': {
      id: '/toast'
      path: '/toast'
      fullPath: '/toast'
      preLoaderRoute: typeof ToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs': {
      id: '/tabs'
      path: '/tabs'
      fullPath: '/tabs'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/separator': {
      id: '/separator'
      path: '/separator'
      fullPath: '/separator'
      preLoaderRoute: typeof SeparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll-area': {
      id: '/scroll-area'
      path: '/scroll-area'
      fullPath: '/scroll-area'
      preLoaderRoute: typeof ScrollAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-card': {
      id: '/preview-card'
      path: '/preview-card'
      fullPath: '/preview-card'
      preLoaderRoute: typeof PreviewCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popover': {
      id: '/popover'
      path: '/popover'
      fullPath: '/popover'
      preLoaderRoute: typeof PopoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogs': {
      id: '/dialogs'
      path: '/dialogs'
      fullPath: '/dialogs'
      preLoaderRoute: typeof DialogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarRoute: AvatarRoute,
  ButtonRoute: ButtonRoute,
  DialogsRoute: DialogsRoute,
  FormRoute: FormRoute,
  MenuRoute: MenuRoute,
  PopoverRoute: PopoverRoute,
  PreviewCardRoute: PreviewCardRoute,
  ScrollAreaRoute: ScrollAreaRoute,
  SeparatorRoute: SeparatorRoute,
  TableRoute: TableRoute,
  TabsRoute: TabsRoute,
  ToastRoute: ToastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
