name: ✈️ Prerelease on NPMJS
run-name: ✈️ Publish ${{ inputs.version }} ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g., 2.0.0)"
        required: true
      tag:
        description: "Tag (e.g., alpha.1)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and enable pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          PNPM_SKIP_BUILD_APPROVAL: 1

      - name: Build project
        run: |
          pnpm build
        env:
          PNPM_SKIP_BUILD_APPROVAL: 1

      - name: Set version
        run: |
          echo "Setting version to ${{ inputs.version }}"
          pnpm version prerelease --preid ${{ inputs.tag }} --no-git-tag-version

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Publish to npmjs
        run: pnpm publish --access public --no-git-checks --tag ${{ inputs.tag }}
