name: ✈️ Publish on NPMJS
run-name: ✈️ Publish ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g., 2.0.0)"
        required: true
      tag:
        description: "Pre-release tag (e.g., alpha.1)"
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          PNPM_SKIP_BUILD_APPROVAL: 1

      - name: Build project
        run: |
          pnpm build
        env:
          PNPM_SKIP_BUILD_APPROVAL: 1

      - name: Set version
        run: |
          echo "Setting version to ${{ inputs.version }} ${{ inputs.tag || 'latest' }}"
          if [ -n "${{ inputs.tag }}" ]; then
            pnpm version ${{ inputs.version }} --no-git-tag-version --prerelease --preid ${{ inputs.tag }}
          else
            pnpm version ${{ inputs.version }} --no-git-tag-version
          fi

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Publish to npmjs
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
           pnpm publish --access public --no-git-checks --tag ${{ inputs.tag }}
          else
            pnpm publish --access public --no-git-checks
          fi
