name: ✈️ Publish on NPMJS
run-name: ✈️ Release ${{ inputs.version }}-${{ inputs.qualifier }}.${{ inputs.qualifier-number }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Target version (e.g., 1.0.0)"
        required: true
      qualifier:
        description: "Qualifier (e.g., release, alpha, beta)"
        required: true
        type: choice
        options:
          - release
          - alpha
          - beta
          - rc
      qualifier-number:
        description: "Pre-release number (e.g., 1, 2,...). Ignored if qualifier is 'release'."
        required: false
        default: "1"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          PNPM_SKIP_BUILD_APPROVAL: 1

      - name: Build project
        run: |
          pnpm build
        env:
          PNPM_SKIP_BUILD_APPROVAL: 1

      - name: Set version
        run: |
          echo "Setting version to ${{ inputs.version }}-${{ inputs.qualifier }}.${{ inputs.qualifier-number }}"
          if [ "${{ inputs.qualifier }}" != "release" ]; then
            pnpm version ${{ inputs.version }}-${{ inputs.qualifier }}.${{ inputs.qualifier-number }} --no-git-tag-version --prerelease --preid ${{ inputs.qualifier }}.${{ inputs.qualifier-number }}
          else
            pnpm version ${{ inputs.version }} --no-git-tag-version
          fi
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Publish to npmjs
        run: |
          if [ "${{ inputs.qualifier }}" != "release" ]; then
            pnpm publish --access public --no-git-checks --tag ${{ inputs.qualifier }}
          else
            pnpm publish --access public --no-git-checks --tag latest
          fi
